import Head from "next/head";
import { useRecoilState, useRecoilValue } from "recoil";
import { counterState, multipleCounterState } from "@/state/atom";
import { useCallback } from "react";

export default function Home() {
  const [count, setCount] = useRecoilState(counterState);
  const multipledCount = useRecoilValue(multipleCounterState(2));

  const increment = useCallback(() => {
    setCount((prev) => prev + 1);
  }, [setCount]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Counter!</h1>

        <table>
          <thead>
            <tr>
              <th>count</th>
              <th>multipled</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{count}</td>
              <td>{multipledCount}</td>
            </tr>
          </tbody>
        </table>

        <button onClick={increment}>increment</button>
      </main>
    </>
  );
}
